title: Page

pages: false

fields:
  title:
    label: Title
    type:  text
    required: true

  coverimage:
    label: Cover Image
    type: image
    required: true
    help: min. 1200px x 1200px

  text:
    label: Text
    type:  textarea
    required: true
